version: '3.6'

networks:
  app: { }

services:
  timescaledb:
    networks:
      - app
    build:
      context: Docker
      dockerfile: timescale.Dockerfile
    environment:
      POSTGRES_PASSWORD: p_318Jhs&2
      POSTGRES_USER: timescale
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U timescale" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  ws-server:
    networks:
      - app
    restart: always
    image: timeseries-study-ws:latest
    ports:
      - 8080:8080
    environment:
      - TIMESCALE_HOST=timescaledb
    depends_on:
      timescaledb:
        condition: service_healthy
