addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.10.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.4.3")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"  % "0.9.29")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"  % "1.0.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"   % "0.6.0")
